### ISSUE TITLE
build docsite was error

### ISSUE THREAD

**Issue by SAMZONG** [higress-group/higress-group.github.io#27]
![20221107153342](https://user-images.githubusercontent.com/13782141/200251685-ca981f28-2601-4cad-a659-a14138bbbf75.png)

```bash
± npm --version
6.4.1

± node --version
v8.16.0

± docsite -V
1.3.11
```
macos m1 max

```bash
± docsite start
(node:63021) UnhandledPromiseRejectionWarning: Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/samzonglu/Git/kubernetes/higress-group.github.io/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/samzonglu/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/@babel/core/lib/config/config-descriptors.js:168:11)
    at createDescriptor.next (<anonymous>)
    at evaluateSync (/Users/samzonglu/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/gensync/index.js:251:28)
    at items.map.item (/Users/samzonglu/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/gensync/index.js:31:34)
    at Array.map (<anonymous>)
    at Function.sync (/Users/samzonglu/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/gensync/index.js:31:22)
    at Function.all (/Users/samzonglu/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/gensync/index.js:210:24)
    at Generator.next (<anonymous>)
    at createDescriptors (/Users/samzonglu/.nvm/versions/node/v8.16.0/lib/node_modules/docsite/node_modules/@babel/core/lib/config/config-descriptors.js:109:41)
    at createDescriptors.next (<anonymous>)
(node:63021) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:63021) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by johnlanni** [comment]
docsite need 1.3.8,  package-lock.json has been added.

**Comment by SpecialYang** [comment]
@SAMZONG Now you can try use docker by which you don't need to solve the dependencies problem. Good luck.
